# Generated by Django 3.0.8 on 2020-08-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0002_remove_project_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='project',
        ),
    ]
